# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[directory]
truncate_to_repo = false

[git_branch]
format = '\[[$branch]($style)\] '

[lua]
format = '\[[lua ($version)]($style)\]'

[nodejs]
format = '\[[node ($version)]($style)\]'

[package]
disabled = true

[rust]
format = '\[[rust ($version)]($style)\]'
